services:
  db:
    image: postgres:15
    container_name: DB
    restart: always
    volumes:
      - ~/.pg.pg_data/bg2b:/var/lib/postgresql/data
    env_file:
      - .env

  bg2b:
    build:
      context: .
    container_name: BG2B
    image: bg2b
    restart: always
    entrypoint: /bg2b/start.sh
    depends_on:
      - db
    volumes:
      - static:/bg2b/static
      - media:/bg2b/media
    env_file:
      - .env
    environment:
      - VIRTUAL_HOST=${ALLOWED_HOST}
      - LETSENCRYPT_HOST=${ALLOWED_HOST}
      - DEFAULT_HOST=${ALLOWED_HOST}

  nginx:
    build:
      context: ./nginx/
    container_name: NGINX
    restart: always
    volumes:
      - static:/bg2b/static
      - media:/bg2b/media
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - bg2b
    ports:
      - "80:80"
      - "443:443"

  acme_companion:
    image: nginxproxy/acme-companion
    container_name: ACME
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
      - certs:/etc/nginx/certs

volumes:
  static:
  media:
  certs:
  vhost:
  html:
  acme: